hdfs:
  namenode:
    replicas: 1
    image: "bde2020/hadoop-namenode"
    port: 8020
    storageClass: "standard"
    storageSize: "1Gi"
  datanode:
    replicas: 3
    image: "bde2020/hadoop-datanode"
    port: 9864
    storageClass: "standard"
    storageSize: "1Gi"
