apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datanode-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.hdfs.datanode.storageSize }}
  storageClassName: {{ .Values.hdfs.datanode.storageClass }}
