apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: namenode-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.hdfs.namenode.storageSize }}
  storageClassName: {{ .Values.hdfs.namenode.storageClass }}
